### ISSUE TITLE
Compatibility with Guards Villager

### ISSUE THREAD

**Issue by ffuentesm** [Spiderman31807/MC-Modded#3]
Seems that the Villager Guard conversion feature Shift+R-Click with an item with the "convertible_guard_item" tag causes the Villager Inventory to show up instead. 
Could you make it so that if you are holding the item with the "convertible_guard_item" tag, it triggers the conversion instead? 
![image](https://github.com/user-attachments/assets/c4ca2f34-c0e3-4ec5-a33a-dc5c3cd9a5e6)

**Comment by Spiderman31807** [comment]
i swear i already fixed this once? i got a report about it and made it so my code executes after its code. yeah.. i just looked at the source code that i uploaded on github it its got the lowest priority still.. same with the NeoForge Versions i uploaded. you sure this is an issue or if your on a past version maybe..?
